/* ============================================================
   Zentory — Predefined product catalog
   ------------------------------------------------------------
   A curated, offline library of common products grouped by
   business sector. Each item carries the fields that are tedious
   to look up manually: unit of measure, GST slab, and HSN code.

   These are STARTING POINTS. Prices are intentionally omitted —
   the shop sets its own cost/selling price when it adds stock.
   GST rates & HSN codes reflect common Indian classifications and
   should be verified against the latest CBIC notifications.
   ============================================================ */
const CATALOG = (() => {
  const sectors = [
    {
      id: 'medical', name: 'Medical / Pharmacy', icon: 'fa-prescription-bottle-medical',
      items: [
        { name: 'Paracetamol 500mg Tablet', unit: 'strip', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'Amoxicillin 500mg Capsule', unit: 'strip', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'Azithromycin 500mg Tablet', unit: 'strip', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'Cetirizine 10mg Tablet', unit: 'strip', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'Pantoprazole 40mg Tablet', unit: 'strip', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'Metformin 500mg Tablet', unit: 'strip', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'Cough Syrup 100ml', unit: 'bottle', gstRate: 12, hsnCode: '3004', category: 'Medicines' },
        { name: 'ORS Powder Sachet', unit: 'pcs', gstRate: 5, hsnCode: '3004', category: 'Medicines' },
        { name: 'Multivitamin Tablet', unit: 'bottle', gstRate: 18, hsnCode: '2106', category: 'Supplements' },
        { name: 'Antiseptic Liquid 500ml', unit: 'bottle', gstRate: 18, hsnCode: '3808', category: 'First Aid' },
        { name: 'Cotton Roll 100g', unit: 'pcs', gstRate: 12, hsnCode: '3005', category: 'First Aid' },
        { name: 'Adhesive Bandage (Pack)', unit: 'pack', gstRate: 12, hsnCode: '3005', category: 'First Aid' },
        { name: 'Surgical Gloves (100pk)', unit: 'box', gstRate: 12, hsnCode: '4015', category: 'Consumables' },
        { name: 'Face Mask 3-Ply (50pk)', unit: 'box', gstRate: 12, hsnCode: '6307', category: 'Consumables' },
        { name: 'Digital Thermometer', unit: 'pcs', gstRate: 12, hsnCode: '9025', category: 'Devices' },
        { name: 'Blood Pressure Monitor', unit: 'pcs', gstRate: 12, hsnCode: '9018', category: 'Devices' },
        { name: 'Glucometer', unit: 'pcs', gstRate: 12, hsnCode: '9018', category: 'Devices' },
        { name: 'Hand Sanitizer 500ml', unit: 'bottle', gstRate: 18, hsnCode: '3808', category: 'Consumables' },
        { name: 'Sanitary Napkins (Pack)', unit: 'pack', gstRate: 0, hsnCode: '9619', category: 'Personal Care' },
        { name: 'N95 Respirator Mask', unit: 'pcs', gstRate: 12, hsnCode: '6307', category: 'Consumables' },
      ],
    },
    {
      id: 'kirana', name: 'Kirana / General Store', icon: 'fa-basket-shopping',
      items: [
        { name: 'Basmati Rice 1kg', unit: 'kg', gstRate: 5, hsnCode: '1006', category: 'Staples' },
        { name: 'Wheat Flour (Atta) 1kg', unit: 'kg', gstRate: 5, hsnCode: '1101', category: 'Staples' },
        { name: 'Toor Dal 1kg', unit: 'kg', gstRate: 5, hsnCode: '0713', category: 'Staples' },
        { name: 'Sugar 1kg', unit: 'kg', gstRate: 5, hsnCode: '1701', category: 'Staples' },
        { name: 'Iodized Salt 1kg', unit: 'kg', gstRate: 5, hsnCode: '2501', category: 'Staples' },
        { name: 'Refined Sunflower Oil 1L', unit: 'litre', gstRate: 5, hsnCode: '1512', category: 'Oils & Ghee' },
        { name: 'Mustard Oil 1L', unit: 'litre', gstRate: 5, hsnCode: '1514', category: 'Oils & Ghee' },
        { name: 'Tea Powder 250g', unit: 'pack', gstRate: 5, hsnCode: '0902', category: 'Beverages' },
        { name: 'Instant Coffee 50g', unit: 'pack', gstRate: 18, hsnCode: '2101', category: 'Beverages' },
        { name: 'Biscuits (Pack)', unit: 'pack', gstRate: 18, hsnCode: '1905', category: 'Packaged Foods' },
        { name: 'Instant Noodles', unit: 'pcs', gstRate: 18, hsnCode: '1902', category: 'Packaged Foods' },
        { name: 'Potato Chips (Pack)', unit: 'pack', gstRate: 12, hsnCode: '2005', category: 'Packaged Foods' },
        { name: 'Soft Drink 750ml', unit: 'bottle', gstRate: 28, hsnCode: '2202', category: 'Beverages' },
        { name: 'Packaged Water 1L', unit: 'bottle', gstRate: 18, hsnCode: '2201', category: 'Beverages' },
        { name: 'Detergent Powder 1kg', unit: 'pack', gstRate: 18, hsnCode: '3402', category: 'Household' },
        { name: 'Bath Soap', unit: 'pcs', gstRate: 18, hsnCode: '3401', category: 'Personal Care' },
        { name: 'Toothpaste 100g', unit: 'pcs', gstRate: 18, hsnCode: '3306', category: 'Personal Care' },
        { name: 'Shampoo Sachet', unit: 'pcs', gstRate: 18, hsnCode: '3305', category: 'Personal Care' },
        { name: 'Milk 500ml', unit: 'pack', gstRate: 0, hsnCode: '0401', category: 'Dairy' },
        { name: 'Eggs (Dozen)', unit: 'dozen', gstRate: 0, hsnCode: '0407', category: 'Dairy' },
        { name: 'Matchbox', unit: 'pcs', gstRate: 5, hsnCode: '3605', category: 'Household' },
        { name: 'Incense Sticks (Pack)', unit: 'pack', gstRate: 5, hsnCode: '3307', category: 'Household' },
      ],
    },
    {
      id: 'restaurant', name: 'Restaurant / Hotel', icon: 'fa-utensils',
      items: [
        { name: 'Onion', unit: 'kg', gstRate: 0, hsnCode: '0703', category: 'Vegetables' },
        { name: 'Tomato', unit: 'kg', gstRate: 0, hsnCode: '0702', category: 'Vegetables' },
        { name: 'Potato', unit: 'kg', gstRate: 0, hsnCode: '0701', category: 'Vegetables' },
        { name: 'Ginger', unit: 'kg', gstRate: 0, hsnCode: '0910', category: 'Vegetables' },
        { name: 'Garlic', unit: 'kg', gstRate: 0, hsnCode: '0703', category: 'Vegetables' },
        { name: 'Paneer 1kg', unit: 'kg', gstRate: 5, hsnCode: '0406', category: 'Dairy' },
        { name: 'Butter 500g', unit: 'pack', gstRate: 12, hsnCode: '0405', category: 'Dairy' },
        { name: 'Cooking Cream 1L', unit: 'litre', gstRate: 12, hsnCode: '0401', category: 'Dairy' },
        { name: 'Basmati Rice 5kg', unit: 'kg', gstRate: 5, hsnCode: '1006', category: 'Staples' },
        { name: 'Wheat Flour 5kg', unit: 'kg', gstRate: 5, hsnCode: '1101', category: 'Staples' },
        { name: 'Refined Oil 15L Tin', unit: 'tin', gstRate: 5, hsnCode: '1512', category: 'Oils & Ghee' },
        { name: 'Garam Masala 500g', unit: 'pack', gstRate: 5, hsnCode: '0910', category: 'Spices' },
        { name: 'Red Chilli Powder 500g', unit: 'pack', gstRate: 5, hsnCode: '0904', category: 'Spices' },
        { name: 'Turmeric Powder 500g', unit: 'pack', gstRate: 5, hsnCode: '0910', category: 'Spices' },
        { name: 'Cumin Seeds 200g', unit: 'pack', gstRate: 5, hsnCode: '0909', category: 'Spices' },
        { name: 'Chicken (Dressed) 1kg', unit: 'kg', gstRate: 0, hsnCode: '0207', category: 'Meat' },
        { name: 'Disposable Food Container', unit: 'pcs', gstRate: 18, hsnCode: '3923', category: 'Packaging' },
        { name: 'Paper Napkin (Pack)', unit: 'pack', gstRate: 18, hsnCode: '4818', category: 'Packaging' },
        { name: 'Aluminium Foil Roll', unit: 'pcs', gstRate: 18, hsnCode: '7607', category: 'Packaging' },
        { name: 'LPG Commercial Cylinder', unit: 'pcs', gstRate: 5, hsnCode: '2711', category: 'Fuel' },
      ],
    },
    {
      id: 'hardware', name: 'Hardware / Electricals', icon: 'fa-screwdriver-wrench',
      items: [
        { name: 'Portland Cement 50kg', unit: 'bag', gstRate: 28, hsnCode: '2523', category: 'Construction' },
        { name: 'TMT Steel Rod 12mm', unit: 'pcs', gstRate: 18, hsnCode: '7214', category: 'Construction' },
        { name: 'Wall Putty 40kg', unit: 'bag', gstRate: 18, hsnCode: '3214', category: 'Construction' },
        { name: 'Emulsion Paint 20L', unit: 'bucket', gstRate: 18, hsnCode: '3209', category: 'Paints' },
        { name: 'Enamel Paint 1L', unit: 'can', gstRate: 18, hsnCode: '3208', category: 'Paints' },
        { name: 'PVC Pipe 1 inch', unit: 'pcs', gstRate: 18, hsnCode: '3917', category: 'Plumbing' },
        { name: 'PVC Elbow Joint', unit: 'pcs', gstRate: 18, hsnCode: '3917', category: 'Plumbing' },
        { name: 'Ball Valve 1/2 inch', unit: 'pcs', gstRate: 18, hsnCode: '8481', category: 'Plumbing' },
        { name: 'Claw Hammer', unit: 'pcs', gstRate: 18, hsnCode: '8205', category: 'Tools' },
        { name: 'Screwdriver Set', unit: 'set', gstRate: 18, hsnCode: '8205', category: 'Tools' },
        { name: 'Measuring Tape 5m', unit: 'pcs', gstRate: 18, hsnCode: '9017', category: 'Tools' },
        { name: 'Hand Drill Machine', unit: 'pcs', gstRate: 18, hsnCode: '8467', category: 'Tools' },
        { name: 'Wood Screws (Box)', unit: 'box', gstRate: 18, hsnCode: '7318', category: 'Fasteners' },
        { name: 'Wall Plug (Pack)', unit: 'pack', gstRate: 18, hsnCode: '3925', category: 'Fasteners' },
        { name: 'Electrical Wire 1.5mm (90m)', unit: 'roll', gstRate: 18, hsnCode: '8544', category: 'Electricals' },
        { name: 'Modular Switch', unit: 'pcs', gstRate: 18, hsnCode: '8536', category: 'Electricals' },
        { name: 'LED Bulb 9W', unit: 'pcs', gstRate: 12, hsnCode: '8539', category: 'Electricals' },
        { name: 'LED Tube Light', unit: 'pcs', gstRate: 12, hsnCode: '9405', category: 'Electricals' },
        { name: 'MCB 16A', unit: 'pcs', gstRate: 18, hsnCode: '8536', category: 'Electricals' },
        { name: 'PVC Insulation Tape', unit: 'pcs', gstRate: 18, hsnCode: '3919', category: 'Electricals' },
      ],
    },
    {
      id: 'electronics', name: 'Electronics', icon: 'fa-plug',
      items: [
        { name: 'Smartphone Charger 20W', unit: 'pcs', gstRate: 18, hsnCode: '8504', category: 'Accessories' },
        { name: 'USB-C Cable 1m', unit: 'pcs', gstRate: 18, hsnCode: '8544', category: 'Accessories' },
        { name: 'Power Bank 10000mAh', unit: 'pcs', gstRate: 18, hsnCode: '8507', category: 'Accessories' },
        { name: 'Wireless Earbuds', unit: 'pcs', gstRate: 18, hsnCode: '8518', category: 'Audio' },
        { name: 'Bluetooth Speaker', unit: 'pcs', gstRate: 18, hsnCode: '8518', category: 'Audio' },
        { name: 'Wired Earphones', unit: 'pcs', gstRate: 18, hsnCode: '8518', category: 'Audio' },
        { name: 'Wireless Mouse', unit: 'pcs', gstRate: 18, hsnCode: '8471', category: 'Computer' },
        { name: 'Mechanical Keyboard', unit: 'pcs', gstRate: 18, hsnCode: '8471', category: 'Computer' },
        { name: 'USB Flash Drive 32GB', unit: 'pcs', gstRate: 18, hsnCode: '8523', category: 'Storage' },
        { name: 'MicroSD Card 64GB', unit: 'pcs', gstRate: 18, hsnCode: '8523', category: 'Storage' },
        { name: 'HDMI Cable 1.5m', unit: 'pcs', gstRate: 18, hsnCode: '8544', category: 'Accessories' },
        { name: 'Laptop Adapter 65W', unit: 'pcs', gstRate: 18, hsnCode: '8504', category: 'Computer' },
        { name: 'Webcam HD 1080p', unit: 'pcs', gstRate: 18, hsnCode: '8525', category: 'Computer' },
        { name: 'Extension Board 4-Socket', unit: 'pcs', gstRate: 18, hsnCode: '8536', category: 'Accessories' },
        { name: 'AA Battery (4pk)', unit: 'pack', gstRate: 18, hsnCode: '8506', category: 'Batteries' },
        { name: 'Mobile Screen Guard', unit: 'pcs', gstRate: 18, hsnCode: '3919', category: 'Accessories' },
        { name: 'Phone Back Cover', unit: 'pcs', gstRate: 18, hsnCode: '3926', category: 'Accessories' },
        { name: 'Smart LED TV 43"', unit: 'pcs', gstRate: 18, hsnCode: '8528', category: 'Appliances' },
      ],
    },
    {
      id: 'garage', name: 'Auto Garage / Service', icon: 'fa-car',
      items: [
        { name: 'Engine Oil 15W-40 (1L)', unit: 'litre', gstRate: 18, hsnCode: '2710', category: 'Lubricants' },
        { name: 'Engine Oil 20W-40 (3.5L)', unit: 'pcs', gstRate: 18, hsnCode: '2710', category: 'Lubricants' },
        { name: 'Gear Oil 1L', unit: 'litre', gstRate: 18, hsnCode: '2710', category: 'Lubricants' },
        { name: 'Brake Fluid DOT 3', unit: 'bottle', gstRate: 18, hsnCode: '3819', category: 'Fluids' },
        { name: 'Coolant 1L', unit: 'bottle', gstRate: 18, hsnCode: '3820', category: 'Fluids' },
        { name: 'Oil Filter', unit: 'pcs', gstRate: 28, hsnCode: '8421', category: 'Filters' },
        { name: 'Air Filter', unit: 'pcs', gstRate: 28, hsnCode: '8421', category: 'Filters' },
        { name: 'Spark Plug', unit: 'pcs', gstRate: 28, hsnCode: '8511', category: 'Engine Parts' },
        { name: 'Brake Pad Set', unit: 'set', gstRate: 28, hsnCode: '8708', category: 'Brakes' },
        { name: 'Clutch Plate', unit: 'pcs', gstRate: 28, hsnCode: '8708', category: 'Transmission' },
        { name: 'Car Battery 35Ah', unit: 'pcs', gstRate: 28, hsnCode: '8507', category: 'Electricals' },
        { name: 'Two-Wheeler Tyre', unit: 'pcs', gstRate: 28, hsnCode: '4011', category: 'Tyres' },
        { name: 'Car Tyre (Tubeless)', unit: 'pcs', gstRate: 28, hsnCode: '4011', category: 'Tyres' },
        { name: 'Wiper Blade', unit: 'pcs', gstRate: 28, hsnCode: '8512', category: 'Accessories' },
        { name: 'Headlight Bulb', unit: 'pcs', gstRate: 28, hsnCode: '8539', category: 'Electricals' },
        { name: 'Grease 500g', unit: 'pcs', gstRate: 18, hsnCode: '2710', category: 'Lubricants' },
        { name: 'Car Wash Shampoo 1L', unit: 'bottle', gstRate: 18, hsnCode: '3402', category: 'Care' },
        { name: 'Chain Lube Spray', unit: 'pcs', gstRate: 18, hsnCode: '2710', category: 'Lubricants' },
      ],
    },
    {
      id: 'stationery', name: 'Stationery / Books', icon: 'fa-pen',
      items: [
        { name: 'A4 Paper Ream (500 sheets)', unit: 'ream', gstRate: 12, hsnCode: '4802', category: 'Paper' },
        { name: 'Notebook 200 Pages', unit: 'pcs', gstRate: 12, hsnCode: '4820', category: 'Notebooks' },
        { name: 'Spiral Notebook', unit: 'pcs', gstRate: 12, hsnCode: '4820', category: 'Notebooks' },
        { name: 'Ball Pen (Blue)', unit: 'pcs', gstRate: 12, hsnCode: '9608', category: 'Writing' },
        { name: 'Gel Pen', unit: 'pcs', gstRate: 12, hsnCode: '9608', category: 'Writing' },
        { name: 'Pencil (HB)', unit: 'pcs', gstRate: 12, hsnCode: '9609', category: 'Writing' },
        { name: 'Eraser', unit: 'pcs', gstRate: 5, hsnCode: '4016', category: 'Writing' },
        { name: 'Sharpener', unit: 'pcs', gstRate: 12, hsnCode: '8214', category: 'Writing' },
        { name: 'Highlighter', unit: 'pcs', gstRate: 12, hsnCode: '9608', category: 'Writing' },
        { name: 'Permanent Marker', unit: 'pcs', gstRate: 12, hsnCode: '9608', category: 'Writing' },
        { name: 'Glue Stick', unit: 'pcs', gstRate: 18, hsnCode: '3506', category: 'Adhesives' },
        { name: 'Stapler', unit: 'pcs', gstRate: 18, hsnCode: '8305', category: 'Office' },
        { name: 'Staple Pins (Box)', unit: 'box', gstRate: 18, hsnCode: '8305', category: 'Office' },
        { name: 'File Folder', unit: 'pcs', gstRate: 18, hsnCode: '4820', category: 'Office' },
        { name: 'Sticky Notes Pad', unit: 'pcs', gstRate: 12, hsnCode: '4820', category: 'Office' },
        { name: 'Scissors', unit: 'pcs', gstRate: 12, hsnCode: '8213', category: 'Office' },
        { name: 'Calculator', unit: 'pcs', gstRate: 18, hsnCode: '8470', category: 'Office' },
        { name: 'Geometry Box', unit: 'pcs', gstRate: 12, hsnCode: '9017', category: 'School' },
      ],
    },
    {
      id: 'apparel', name: 'Apparel / Clothing', icon: 'fa-shirt',
      items: [
        { name: "Men's Cotton T-Shirt", unit: 'pcs', gstRate: 5, hsnCode: '6109', category: 'Menswear' },
        { name: "Men's Formal Shirt", unit: 'pcs', gstRate: 5, hsnCode: '6205', category: 'Menswear' },
        { name: "Men's Jeans", unit: 'pcs', gstRate: 12, hsnCode: '6203', category: 'Menswear' },
        { name: "Men's Trousers", unit: 'pcs', gstRate: 12, hsnCode: '6203', category: 'Menswear' },
        { name: "Women's Kurti", unit: 'pcs', gstRate: 5, hsnCode: '6211', category: 'Womenswear' },
        { name: 'Saree', unit: 'pcs', gstRate: 5, hsnCode: '6211', category: 'Womenswear' },
        { name: 'Leggings', unit: 'pcs', gstRate: 5, hsnCode: '6104', category: 'Womenswear' },
        { name: "Women's Top", unit: 'pcs', gstRate: 5, hsnCode: '6106', category: 'Womenswear' },
        { name: 'Kids T-Shirt', unit: 'pcs', gstRate: 5, hsnCode: '6109', category: 'Kidswear' },
        { name: 'Kids Frock', unit: 'pcs', gstRate: 5, hsnCode: '6111', category: 'Kidswear' },
        { name: 'Innerwear (Pack)', unit: 'pack', gstRate: 12, hsnCode: '6107', category: 'Innerwear' },
        { name: 'Socks (Pair)', unit: 'pair', gstRate: 12, hsnCode: '6115', category: 'Accessories' },
        { name: 'Handkerchief (Pack)', unit: 'pack', gstRate: 5, hsnCode: '6213', category: 'Accessories' },
        { name: 'Woollen Sweater', unit: 'pcs', gstRate: 12, hsnCode: '6110', category: 'Winterwear' },
        { name: 'Jacket', unit: 'pcs', gstRate: 12, hsnCode: '6201', category: 'Winterwear' },
        { name: 'Dupatta / Stole', unit: 'pcs', gstRate: 5, hsnCode: '6214', category: 'Accessories' },
        { name: 'Bath Towel', unit: 'pcs', gstRate: 5, hsnCode: '6302', category: 'Home Textile' },
        { name: 'Bedsheet (Double)', unit: 'pcs', gstRate: 5, hsnCode: '6302', category: 'Home Textile' },
      ],
    },
  ];

  // Stable-ish colors used when auto-creating categories from the catalog.
  const palette = ['#6366f1', '#f59e0b', '#22c55e', '#8b5cf6', '#ef4444', '#06b6d4', '#f97316', '#ec4899', '#14b8a6', '#3b82f6'];
  function colorFor(name) {
    let h = 0;
    for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0;
    return palette[h % palette.length];
  }

  return { sectors, colorFor };
})();
